[package]
name = "slob"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.80"
quote = "1.0"
sqlparser = "0.12.0"
regex = "1.5.4"
proc-macro2 = "1.0.30"
